config/routes.rb
Memoizr::Application.routes.draw do
  resource :game do
    resources :reveals do
      collection do
        get 'check' 
      end
      member do
        get 'old'
      end
    end
  end

  match '/game/destroy', :to =>'games#destroy'
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/login', :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy'
  match '/lobby', :to => 'lobbies#index'
  match '/back_to_lobby', :to => 'lobbies#back'
  match '/check_lobby', :to => 'lobbies#check'
  match '/wait', :to => 'lobbies#wait'
  match '/start', :to => 'lobbies#start'
  match '/users', :to => 'lobbies#users'
  match '/multi_game', :to => 'lobbies#create'
  match '/game/:game_id/join', :to => 'games#join', :as => 'join_game'
  match '/facepalm', :to => 'sessions#facepalm'
  root :to => "games#show"

end

app/controllers/lobbies_controller.rb
class LobbiesController < ApplicationController
  before_filter :check_permission

  def index
    @game = Game::Multi.new( :max_players => 4)
  end

  def check; end

  def create
    cancel_game
    @game = Game::Multi.new(params[:game])
    if @game.save
      session[:current_game_id] = @game.id
      current_user.update_attribute(:game_id, @game.id)
      render :action => :wait
    else
      render :action => :index
    end
  end

  def wait
    @game = Game::Multi.find(current_user.game_id)
  rescue
    quit_game
  end

  def users
    @game = Game::Multi.find(current_user.game_id)
    quit_game if @game.canceled?
  rescue
    quit_game
  end

  def start
    @game = Game::Multi.find(current_user.game_id)
    @game.start!
    redirect_to game_path
  rescue
    session[:current_game_id] = nil
    redirect_to lobby_path
  end

  def back
    cancel_game
    redirect_to :action => :index
  end

end

app/views/lobbies/_lobby.html.haml
#lobby
  - if Game::Multi.created.empty?
    %p There are no open games... why don't you start a new one?
  - else
    %table
      %tr
        %th Players
        %th{ :width => 100 } &nbsp;
      - Game::Multi.created.latests.each do |game|
        - if game.users.count == 0
          -  game.delete
        - else
          %tr
            %td
              = game.users.map(&:name).join(", ")
              .right
                created
                = distance_of_time_in_words_to_now(game.created_at)
                ago
            %td
              - if game.has_user?(current_user)
                = link_to 'back to game', join_game_path(game)
              - elsif game.can_be_joined? 
                = link_to 'join this game', join_game_path(game)

  .clear.prepend-top
    %table
      %tr
        %th.center{ :colspan => 2 } SYSTEM STATS
      %tr
        %td.r Games in progress
        %td.r{ :width => 40 }= Game.where( :state => 'playing').count 
      %tr
        %td.r Games completed
        %td.r{ :width => 40 }= Game.where( :state => 'finished').count 
    -#
      %p
        Games in progress:
        = Game.where( :state => 'playing').count

        %br
        Games completed:
        = Game.where( :state => 'finished').count

app/views/lobbies/_users.html.haml
%ul#users_list
  - game.users.each do |user|
    %li=h user.name

app/views/lobbies/check.js.erb
$('#lobby').replaceWith("<%= escape_javascript(render :partial => 'lobby.html.haml')%>");

app/views/lobbies/index.html.haml
%h2
  Welcome to the
  = flickrify("multiplayr")
  lobby,
  = current_user.name

.clear

= render :partial => 'lobbies/lobby'

%h2{ :style => 'margin-top: 1em' }
  Start a new
  = flickrify("multiplayr")
  game

= form_for(:game, @game, :url => multi_game_path, :method => :post, :html => { :class => 'clear' }) do |f|
  = f.text_field :images_category, :placeholder => 'choose a topic (e.g. plants)'
  %span or just click &rarr;
  %button{ :type => 'submit' } Start game!
  .clear.error= @game.errors[:images_category]

.divider

.clear.prepend-top
  %a.button{ :href => '/logout' }
    %img{ :src => "/images/door-open-out.png"}
    Logout

app/views/lobbies/users.js.erb
<% if @game.playing? %>
  window.location = '/game';
<% else %>
  $('#users_list').replaceWith("<%= escape_javascript(render :partial => 'users.html.haml', :locals => { :game => @game } )%>");
<% end %>

app/views/lobbies/wait.html.haml
.span-12.prepend-8.last
  %h2 
    = flickrify('Playr')
    list

  .clear
    = render :partial => 'lobbies/users', :locals => { :game => @game }
    We are waiting for the game owner to start the game.

  = link_to 'Back to lobby', back_to_lobby_path
- if @game.is_current_user_owner?
  .span-24.last.prepend-top
    = link_to 'Start', start_path, :confirm => 'Are you ready to bring it on?', :class => 'button'